---
# tasks file for opuk.common

- name: install common packages
  package: 
    name: "{{ item }}" 
    state: present
  with_items:
    - libselinux-python
    - vim-enhanced

- name: set motd
  template: src=motd.j2 dest=/etc/motd
  when: set_motd == True

- name: create users
  user: 
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups | default() }}"
  with_items: "{{ users | default([]) }}"

 

